Repository zeshuaro/appainter, pull requests merged in 2022-03, with the labels that each got.

#301 refactor: update enum model methods names
  lib/app_bar_theme/cubit/app_bar_theme_cubit.dart
  lib/app_bar_theme/view/app_bar_theme_editor.dart
  lib/input_decoration_theme/cubit/input_decoration_theme_cubit.dart
  lib/input_decoration_theme/view/input_decoration_theme_editor.dart
  lib/models/enums/enum_model.dart
  lib/text_theme/cubits/abstract_text_style_cubit.dart
  lib/widgets/cards/text_style_card.dart
  test/app_bar_theme/app_bar_theme_cubit_test.dart
  test/app_bar_theme/app_bar_theme_editor_test.dart
  test/input_decoration_theme/input_decoration_theme_cubit_test.dart
  test/input_decoration_theme/input_decoration_theme_editor_test.dart
  test/models/enums/enum_model_test.dart
  test/text_theme/cubits/abstract_text_style_cubit.dart
  test/text_theme/views/abstract_text_style_editor.dart
Labels: refactor

#308 ci: split release workflow
  .github/workflows/github_actions.yml
  .github/workflows/release.yml
Labels: ci

#334 chore(deps): update dependencies
  example/pubspec.lock
  pubspec.lock
Labels: dependencies

#337 ci: update renovate flutter update commit scope
  renovate.json
Labels: ci

#338 ci: add close stale issues and prs workflow
  .github/stale.yml
  .github/workflows/close_stale.yml
Labels: ci

#336 fix: advanced theme not exporting correct color scheme
  lib/home/widgets/export_button.dart
  test/home/views/home_page_test.dart
  test/home/widgets/export_button_test.dart
Labels: bug

#339 docs: add funding config
  .github/FUNDING.yml
Labels: ignore

#340 chore: fix window size package url
  pubspec.lock
  pubspec.yaml
Labels: dependencies, ignore

#341 chore(deps): update dependencies
  pubspec.lock
Labels: dependencies

#345 fix: reset seed color when theme brightness updated
  lib/basic_theme/cubit/basic_theme_cubit.dart
  test/basic_theme/basic_theme_cubit_test.dart
Labels: bug

#347 ci: remove renovate dev dependencies grouping
  renovate.json
Labels: ci

#350 chore(deps): update dependencies
  pubspec.lock
Labels: dependencies

#353 feat: add secondary color picker for advanced theme
  lib/color_theme/cubit/color_theme_cubit.dart
  lib/color_theme/view/color_theme_editor.dart
  test/color_theme/color_theme_cubit_test.dart
  test/color_theme/color_theme_editor_test.dart
Labels: enhancement

#356 docs: update usage docs with fully functional example code
  USAGE.md
Labels: documentation

#357 chore(deps): update dependencies
  example/pubspec.lock
  pubspec.lock
Labels: dependencies

#358 feat: add app bar actions icon theme editor
  lib/app_bar_theme/cubit/app_bar_theme_cubit.dart
  lib/app_bar_theme/view/app_bar_theme_editor.dart
  lib/icon_theme/view/icon_theme_editor.dart
  lib/widgets/cards/icon_theme_card.dart
  macos/Podfile.lock
  test/app_bar_theme/app_bar_theme_cubit_test.dart
  test/app_bar_theme/app_bar_theme_editor_test.dart
  test/icon_theme/icon_theme_editor_test.dart
Labels: enhancement
